---
- hosts: network
  become: yes
  tasks:
#    - name: Backing up configurations
    - include: roles/config_manager/configs-backup.yml
    - name: Fetch the latest update meta-data from the repository
      apt: update_cache=yes
    - name: Upgrade all the packages to the latest distribution
      apt: upgrade=dist
  handlers:
    - include: handlers/main.yml
