# -*- mode: ruby -*-
# vi: set ft=ruby :

groups = {
  "spines" => ["spine1", "spine2"],
  "leafs" => ["leaf1", "leaf2", "leaf3", "leaf4", "leaf5", "leaf6"],
  "servers" => ["server1", "server2", "server3"],
  "network:children" => ["spines", "leafs"],
  "a-leafs" => ["leaf1", "leaf3", "leaf5"],
  "b-leafs" => ["leaf2", "leaf4", "leaf6"],
  "a-spines" => ["spine1"],
  "b-spines" => ["spine2"]
}


Vagrant.configure("2") do |config|

  cumulus_image = "CumulusCommunity/cumulus-vx"
  link_seed = Random.rand(999.999).to_s

  config.vm.define "leaf1" do |leaf1| 
    leaf1.vm.box = cumulus_image
    leaf1.vm.network "private_network",  virtualbox__intnet: 'leaf1-spine1-' + link_seed, auto_config: false
    leaf1.vm.network "private_network",  virtualbox__intnet: 'leaf1-spine2-' + link_seed, auto_config: false
    leaf1.vm.network "private_network",  virtualbox__intnet: 'leaf1-leaf2-peerlink1-' + link_seed, auto_config: false
    leaf1.vm.network "private_network",  virtualbox__intnet: 'leaf1-leaf2-peerlink2-' + link_seed, auto_config: false
    leaf1.vm.network "private_network",  virtualbox__intnet: 'leaf1-server1-' + link_seed, auto_config: false
    leaf1.vm.host_name = "leaf1"
    
    leaf1.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      #ansible.verbose = "vvv"
      ansible.playbook = "provision.yml"
    end

    leaf1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end
  
  config.vm.define "leaf2" do |leaf2|
    leaf2.vm.box = cumulus_image 
    leaf2.vm.network "private_network",  virtualbox__intnet: 'leaf2-spine1-' + link_seed, auto_config: false
    leaf2.vm.network "private_network",  virtualbox__intnet: 'leaf2-spine2-' + link_seed, auto_config: false
    leaf2.vm.network "private_network",  virtualbox__intnet: 'leaf1-leaf2-peerlink1-' + link_seed, auto_config: false
    leaf2.vm.network "private_network",  virtualbox__intnet: 'leaf1-leaf2-peerlink2-' + link_seed, auto_config: false
    leaf2.vm.network "private_network",  virtualbox__intnet: 'leaf2-server1-' + link_seed, auto_config: false
    leaf2.vm.host_name = "leaf2"
    
    leaf2.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    leaf2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "leaf3" do |leaf3| 
    leaf3.vm.box = cumulus_image
    leaf3.vm.network "private_network",  virtualbox__intnet: 'leaf3-spine1-' + link_seed, auto_config: false
    leaf3.vm.network "private_network",  virtualbox__intnet: 'leaf3-spine2-' + link_seed, auto_config: false
    leaf3.vm.network "private_network",  virtualbox__intnet: 'leaf3-leaf4-peerlink1-' + link_seed, auto_config: false
    leaf3.vm.network "private_network",  virtualbox__intnet: 'leaf3-leaf4-peerlink2-' + link_seed, auto_config: false
    leaf3.vm.network "private_network",  virtualbox__intnet: 'leaf3-server2-' + link_seed, auto_config: false
    leaf3.vm.host_name = "leaf3"
    
    leaf3.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    leaf3.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "leaf4" do |leaf4| 
    leaf4.vm.box = cumulus_image
    leaf4.vm.network "private_network",  virtualbox__intnet: 'leaf4-spine1-' + link_seed, auto_config: false
    leaf4.vm.network "private_network",  virtualbox__intnet: 'leaf4-spine2-' + link_seed, auto_config: false
    leaf4.vm.network "private_network",  virtualbox__intnet: 'leaf3-leaf4-peerlink1-' + link_seed, auto_config: false
    leaf4.vm.network "private_network",  virtualbox__intnet: 'leaf3-leaf4-peerlink2-' + link_seed, auto_config: false
    leaf4.vm.network "private_network",  virtualbox__intnet: 'leaf4-server2-' + link_seed, auto_config: false
    leaf4.vm.host_name = "leaf4"
    
    leaf4.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    leaf4.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end
  
  config.vm.define "leaf5" do |leaf5| 
    leaf5.vm.box = cumulus_image
    leaf5.vm.network "private_network",  virtualbox__intnet: 'leaf5-spine1-' + link_seed, auto_config: false
    leaf5.vm.network "private_network",  virtualbox__intnet: 'leaf5-spine2-' + link_seed, auto_config: false
    leaf5.vm.network "private_network",  virtualbox__intnet: 'leaf5-leaf6-peerlink1-' + link_seed, auto_config: false
    leaf5.vm.network "private_network",  virtualbox__intnet: 'leaf5-leaf6-peerlink2-' + link_seed, auto_config: false
    leaf5.vm.network "private_network",  virtualbox__intnet: 'leaf5-server3-' + link_seed, auto_config: false
    leaf5.vm.host_name = "leaf5"
    
    leaf5.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    leaf5.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "leaf6" do |leaf6| 
    leaf6.vm.box = cumulus_image
    leaf6.vm.network "private_network",  virtualbox__intnet: 'leaf6-spine1-' + link_seed, auto_config: false
    leaf6.vm.network "private_network",  virtualbox__intnet: 'leaf6-spine2-' + link_seed, auto_config: false
    leaf6.vm.network "private_network",  virtualbox__intnet: 'leaf5-leaf6-peerlink1-' + link_seed, auto_config: false
    leaf6.vm.network "private_network",  virtualbox__intnet: 'leaf5-leaf6-peerlink2-' + link_seed, auto_config: false
    leaf6.vm.network "private_network",  virtualbox__intnet: 'leaf6-server3-' + link_seed, auto_config: false
    leaf6.vm.host_name = "leaf6"

    leaf6.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    leaf6.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc7", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc8", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc9", "allow-vms"]
    end
  end

  config.vm.define "spine1" do |spine1| 
    spine1.vm.box = cumulus_image
    spine1.vm.network "private_network",  virtualbox__intnet: 'leaf1-spine1-' + link_seed, auto_config: false
    spine1.vm.network "private_network",  virtualbox__intnet: 'leaf2-spine1-' + link_seed, auto_config: false
    spine1.vm.network "private_network",  virtualbox__intnet: 'leaf3-spine1-' + link_seed, auto_config: false
    spine1.vm.network "private_network",  virtualbox__intnet: 'leaf4-spine1-' + link_seed, auto_config: false
    spine1.vm.network "private_network",  virtualbox__intnet: 'leaf5-spine1-' + link_seed, auto_config: false
    spine1.vm.network "private_network",  virtualbox__intnet: 'leaf6-spine1-' + link_seed, auto_config: false
    spine1.vm.network "private_network",  virtualbox__intnet: 'spine1-spine2-peerlink1-' + link_seed, auto_config: false
    spine1.vm.network "private_network",  virtualbox__intnet: 'spine1-spine2-peerlink2-' + link_seed, auto_config: false
    spine1.vm.host_name = "spine1"
    
    spine1.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    spine1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc7", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc8", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc9", "allow-vms"]
    end
  end

  config.vm.define "spine2" do |spine2| 
    spine2.vm.box = cumulus_image
    spine2.vm.network "private_network",  virtualbox__intnet: 'leaf1-spine2-' + link_seed, auto_config: false
    spine2.vm.network "private_network",  virtualbox__intnet: 'leaf2-spine2-' + link_seed, auto_config: false
    spine2.vm.network "private_network",  virtualbox__intnet: 'leaf3-spine2-' + link_seed, auto_config: false
    spine2.vm.network "private_network",  virtualbox__intnet: 'leaf4-spine2-' + link_seed, auto_config: false
    spine2.vm.network "private_network",  virtualbox__intnet: 'leaf5-spine2-' + link_seed, auto_config: false
    spine2.vm.network "private_network",  virtualbox__intnet: 'leaf6-spine2-' + link_seed, auto_config: false
    spine2.vm.network "private_network",  virtualbox__intnet: 'spine1-spine2-peerlink1-' + link_seed, auto_config: false
    spine2.vm.network "private_network",  virtualbox__intnet: 'spine1-spine2-peerlink2-' + link_seed, auto_config: false
    spine2.vm.host_name = "spine2"
    
    spine2.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    spine2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc7", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc8", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc9", "allow-vms"]
    end

  end

  config.vm.define "server1" do |server1| 
    server1.vm.box = cumulus_image
    server1.vm.network "private_network",  virtualbox__intnet: 'leaf1-server1-' + link_seed, auto_config: false
    server1.vm.network "private_network",  virtualbox__intnet: 'leaf2-server1-' + link_seed, auto_config: false
    server1.vm.host_name = "server1"
    
    server1.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    server1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end
  end
  
  config.vm.define "server2" do |server2| 
    server2.vm.box = cumulus_image
    server2.vm.network "private_network",  virtualbox__intnet: 'leaf3-server2-' + link_seed, auto_config: false
    server2.vm.network "private_network",  virtualbox__intnet: 'leaf4-server2-' + link_seed, auto_config: false
    server2.vm.host_name = "server2"
    
    server2.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    server2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end
  end

  config.vm.define "server3" do |server3| 
    server3.vm.box = cumulus_image
    server3.vm.network "private_network",  virtualbox__intnet: 'leaf5-server3-' + link_seed, auto_config: false
    server3.vm.network "private_network",  virtualbox__intnet: 'leaf6-server3-' + link_seed, auto_config: false
    server3.vm.host_name = "server3"
    
    server3.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    server3.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end
  end


end
